### PR TITLE
RPP Tensor Normalize ND on HOST and HIP

### PR DESCRIPTION
**Pull request by r-abishek**
- Adds support for Tensor Normalize ND on HOST and HIP
- Adds relevant Unit/Perf/QA tests

### CODE REVIEW

**Review by lpaoletti — APPROVED** [review]

**Comment by kiritigowda** [comment]
@r-abishek -- needs conflicts resolved

**Comment by kiritigowda** [comment]
@r-abishek needs merge conflicts resolved

**Comment by rrawther** [comment]
@LakshmiKumar23 : Can you please review this PR

**Review by rrawther — APPROVED** [review]

**Comment by kiritigowda** [comment]
@r-abishek -- merge conflicts resolved to merge

**Comment by kiritigowda** [comment]
@r-abishek -- some more conflicts

**Comment by r-abishek** [comment]
@kiritigowda Merge conflicts fixed.

All Audio HOST passing:
image

All Normalize ND HOST passing:
image

**Pull request merged**
